package com.mycollab.core.utils;

import org.junit.Assert;
import org.junit.Test;

import com.diffblue.deeptestutils.Reflector;

public class FileUtilsTest {

  /* testedClasses: FileUtils */

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 92 branch to line 92
   */

  @Test
  public void com_mycollab_core_utils_FileUtils_getVolumeDisplay_000_362b5557985de154() throws Throwable {

    String retval;
    {
      /* Arrange */
      Long volume = null;

      /* Act */
      retval = com.mycollab.core.utils.FileUtils.getVolumeDisplay(volume);
    }
    {
      /* Assert result */
      Assert.assertNotNull(retval);
      Assert.assertEquals("0 Kb", retval);
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 92 branch to line 93
   * conditional line 93 branch to line 93
   */

  @Test
  public void com_mycollab_core_utils_FileUtils_getVolumeDisplay_000_65eb261d97cb7198() throws Throwable {

    String retval;
    {
      /* Arrange */
      Long param_0 = (Long) Reflector.getInstance("java.lang.Long");
      Reflector.setField(param_0, "value", 8L);
      Long volume = param_0;

      /* Act */
      retval = com.mycollab.core.utils.FileUtils.getVolumeDisplay(volume);
    }
    {
      /* Assert result */
      Assert.assertNotNull(retval);
      Assert.assertEquals("8 Bytes", retval);
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 92 branch to line 92
   */

  @Test
  public void com_mycollab_core_utils_FileUtils_getVolumeDisplay_001_362b5557985de154() throws Throwable {

    String retval;
    {
      /* Arrange */
      Long volume = null;

      /* Act */
      retval = com.mycollab.core.utils.FileUtils.getVolumeDisplay(volume);
    }
    {
      /* Assert result */
      Assert.assertNotNull(retval);
      Assert.assertEquals("0 Kb", retval);
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 92 branch to line 93
   * conditional line 93 branch to line 93
   */

  @Test
  public void com_mycollab_core_utils_FileUtils_getVolumeDisplay_001_3d6bed561c0cd31f() throws Throwable {

    String retval;
    {
      /* Arrange */
      Long param_0 = (Long) Reflector.getInstance("java.lang.Long");
      Reflector.setField(param_0, "value", 3L);
      Long volume = param_0;

      /* Act */
      retval = com.mycollab.core.utils.FileUtils.getVolumeDisplay(volume);
    }
    {
      /* Assert result */
      Assert.assertNotNull(retval);
      Assert.assertEquals("3 Bytes", retval);
    }
  }
}
